export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const LOAD_UNIVERSITES_LOADING = 'REDUX_THUNK_LOAD_UNIVERSITES_LOADING';
export const LOAD_UNIVERSITES_SUCCESS = 'REDUX_THUNK_LOAD_UNIVERSITES_SUCCESS';
export const LOAD_UNIVERSITES_ERROR = 'REDUX_THUNK_LOAD_UNIVERSITES_ERROR';
